name: Android Feature Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!develop'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
